CREATE TABLE IF NOT EXISTS `#__mdcar_cars` (
  `mdcar_car_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `kenteken` varchar(255) NOT NULL DEFAULT '',
  `merk` varchar(255) DEFAULT '',
  `type` varchar(255) DEFAULT '',
  `kmstand_start` varchar(255) DEFAULT '',
  `winterbandencorrectie` varchar(255) DEFAULT '',
  `totaalverbuik` varchar(255) DEFAULT '',
  `totaalbedrag` varchar(255) DEFAULT '',
  `gemverbruik` varchar(255) DEFAULT '',
  `access` int(5) NOT NULL DEFAULT '1',
  `ordering` int(10) NOT NULL DEFAULT '0',
  `enabled` tinyint(3) NOT NULL DEFAULT '0',
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) unsigned NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) unsigned NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`mdcar_car_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__mdcar_receipts` (
  `mdcar_receipt_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `mdcar_car_id` bigint(20) NOT NULL,
  `winterbanden` varchar(255) DEFAULT '',
  `kmstand_tank` varchar(255) DEFAULT '',
  `liters` varchar(255) DEFAULT '',
  `liter_prijs` varchar(255) DEFAULT '',
  `tankbedrag` varchar(255) DEFAULT '',
  `gereden_km` varchar(255) DEFAULT '',
  `tankdatum` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mdcar_receipt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
